In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle


df = pd.read_csv('data.csv')
# print("data=\n",df)

df = shuffle(df).reset_index(drop=True)
# print("Shuffled data =\n",df)
df = df.drop(df.columns[[0, 1]], axis=1)
# print(df)


X = df.iloc[:,:-1].values # make X data into matrix/array
print("X=\n",X)

y = df.iloc[:,-1].values # make y data into matrix/array
print("y=\n",y)



from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("X Training = \n",X_train)
print("X Test = \n",X_test)
print("y Training = \n",y_train)
print("y Test = \n",y_test)


X=
 [[   50  2000 16000 ...     3     6    60]
 [   50  2000 16000 ...     3     5    40]
 [   92  2000  8000 ...     1     6    60]
 ...
 [  700   256  2000 ...     1     1    24]
 [   56  2000  8000 ...     1     8    24]
 [  125  2000  8000 ...     2    14    52]]
y=
 [  74   74   53   18   47   20   18   47   19   82   59  227  267   47
   54   22   41   29   28   37   28  117   30   47   20   28  138   74
   72   28   20   15   39   30 1238   41   28   42  253   50   35   28
  749   18   25   18  361   24   86  128   34   74  142   19   24   35
   44   56   64  132   67   24  360   25  119   43   22   25   24  381
  603  117   21   23   33   54  183  350   34   95   46  253   38   21
   34   23   46   42   18  341  126   28   31   23   20   20  116   67
  919  381   50  382  102  175   76   27   57   28   52  190   24  281
  113   31   30   40   46   21   88  275  181  120   32  978   36   26
   34   36   37   29   32   82  107  220   20  151  171   74   70   53
   76   73   33  2

## Backward Elimination

In [47]:
(len(y),1)


(208, 1)

In [48]:
import statsmodels.formula.api as sm
X = np.append(arr=np.ones((len(y),1)).astype(int), values=X, axis=1)

X_opt = X[:,[0,1,2,3,4,5,6]]
reg_optimal = sm.OLS(endog=y, exog=X_opt).fit()
reg_optimal.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.912
Model:                            OLS   Adj. R-squared:                  0.909
Method:                 Least Squares   F-statistic:                     346.7
Date:                Mon, 06 Aug 2018   Prob (F-statistic):          4.14e-103
Time:                        01:11:56   Log-Likelihood:                -1091.0
No. Observations:                 208   AIC:                             2196.
Df Residuals:                     201   BIC:                             2219.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -66.6266      6.262    -10.640      0.000     -78.974     -54.280
x1             0.0669      0.014      4.901      0.000       0.040       0.094
x2             0.0142      0.001      9.936      0.000       0.011       0.017
x3             0.0064      0.001     12.495      0.000       0.005       0.007
x4             0.5846      0.122      4.807      0.000       0.345       0.824
x5            -0.2960      0.670     -0.442      0.659      -1.617       1.025
x6             1.2759      0.177      7.202      0.000       0.927       1.625
==============================================================================
Omnibus:                      108.020   Durbin-Watson:                   1.842
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1039.748
Skew:                           1.747   Prob(JB):                    1.67e-226
Kurtosis:                      13.381   Cond. No.                     3.32e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## SKlearn Model 

In [49]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
print(y_pred)

from sklearn.metrics import r2_score
r21 = r2_score(y_test,y_pred)
print('\nr squared of the model = ',r2)

[ 3.28421322e+02  2.40203509e+01  1.96248914e+00  5.00346818e+01
  5.27039118e+01  2.78312379e+01  2.06091847e+01  2.18191081e+01
  2.00738100e+02  1.03874542e+02 -1.59937396e+01  5.82476813e+01
  1.36335078e+02  3.98768480e+01  1.27716942e+02  3.93304376e+01
  2.37687671e+01  4.20811170e+01  5.42809675e+00  3.60660479e+01
  3.32394623e+01  4.09986854e+00  5.74556019e+01  2.14151423e+01
  2.05466581e+01 -4.00702029e-01  8.00770534e+00  3.26990881e+01
 -3.55803593e+00  4.92994078e+02  6.42415132e+01  3.51047053e+01
  6.90076847e+01  1.35367297e+02  1.27652506e+02  4.82828270e+01
  5.76298111e+01  7.15435894e+01  3.77266750e+01  2.07752466e+02
  1.52047962e+01  7.81657538e+00]

r squared of the model =  0.95904480650653


In [50]:
## SKlearn with backward elimination applied 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle


df = pd.read_csv('data.csv')
# print("data=\n",df)

df = shuffle(df).reset_index(drop=True)
# print("Shuffled data =\n",df)
df = df.drop(df.columns[[0, 1,7]], axis=1)
# print(df)


X = df.iloc[:,:-1].values # make X data into matrix/array
# print("X=\n",X)

y = df.iloc[:,-1].values # make y data into matrix/array
# print("y=\n",y)



from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# print("X Training = \n",X_train)
# print("X Test = \n",X_test)
# print("y Training = \n",y_train)
# print("y Test = \n",y_test)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
print(y_pred)

from sklearn.metrics import r2_score
r22 = r2_score(y_test,y_pred)
print('\nr squared of the model = ',r2)

[ 1.34814025e+01  4.27942972e+01  7.78994124e+01 -5.71472506e+00
  4.90496783e+01  1.05101339e+01  1.26100535e+01  3.55330259e+01
  4.23115733e+02  2.61937158e+01  3.47988508e+01  6.16381162e+01
  1.61713592e+01  2.75189563e+02  2.97417694e+02  1.89151648e+02
  3.03314940e+01  3.90587827e+01  7.01990802e+01  2.43691677e+02
  4.35276638e+02 -6.61787944e+00  1.03144756e+02  2.70473963e+01
  1.14411571e+02  1.70543063e+02  8.72862015e+01  3.27607700e-01
  5.96054399e+01  7.44261902e+01  3.37897699e+01  3.99048015e+01
  9.97416263e+02  2.72526269e+02  1.77551424e+01  5.10528431e+01
  3.62134772e+01  2.18898484e+02 -1.18740162e+01  9.66595599e+00
  1.78541546e+02  2.63646536e+01]

r squared of the model =  0.95904480650653


In [51]:
print('Accuracy incresed by {} by using backward elimination method'.format(r22-r21))

Accuracy incresed by 0.05965404081558656 by using backward elimination method
